In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(my_list)

list

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.arange(3.0)

array([0., 1., 2.])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10)

array([], dtype=int32)

In [15]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [18]:
np.arange(-30,20)

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [19]:
np.arange(10,10)

array([], dtype=int32)

In [20]:
np.arange()

TypeError: arange() requires stop to be specified.

In [21]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [22]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [23]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [24]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros(5, dtype = int )

array([0, 0, 0, 0, 0])

In [27]:
np.zeros((2,2,), dtype=int)

array([[0, 0],
       [0, 0]])

In [29]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [30]:
zero = np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [31]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [36]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [41]:
n

(6, 7)

In [42]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [43]:
np.ones(n,dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [44]:
np.twos(n)

AttributeError: module 'numpy' has no attribute 'twos'

In [45]:
np.threes(n)

AttributeError: module 'numpy' has no attribute 'threes'

In [46]:
np.ones(2)

array([1., 1.])

In [47]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [49]:
np.twos(2,4)

AttributeError: module 'numpy' has no attribute 'twos'

In [50]:
range(5)

range(0, 5)

In [51]:
r = range(5)
r

range(0, 5)

In [52]:
for i in r:
    print(i)

0
1
2
3
4


In [53]:
list(range(5))

[0, 1, 2, 3, 4]

In [54]:
range(1,10)

range(1, 10)

In [55]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
list(range(1,10,3))

[1, 4, 7]

In [56]:
y = list(range(1,10))
y

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
y1 = list(range(12))
y1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [60]:
rand(3,2)

NameError: name 'rand' is not defined

In [61]:
rad(3,2)
random.rand(3,2)

NameError: name 'rad' is not defined

In [62]:
np.random.rand(5)

array([0.50580451, 0.50651063, 0.87256729, 0.71085669, 0.14084159])

In [63]:
np.rand(5)

AttributeError: module 'numpy' has no attribute 'rand'

In [64]:
np.random.rand(2,4)

array([[0.45326884, 0.11238251, 0.99403338, 0.05728493],
       [0.45931167, 0.37658422, 0.05457096, 0.8595753 ]])

In [65]:
np.random.randint(2,4)

2

In [66]:
np.random.rand(2,20)

array([[0.19979325, 0.90348294, 0.80626356, 0.27044677, 0.57758031,
        0.91514422, 0.67969248, 0.13751223, 0.5190566 , 0.05007211,
        0.95921475, 0.19508312, 0.08647692, 0.83287512, 0.75841875,
        0.37405836, 0.43623368, 0.48073469, 0.56457297, 0.87310153],
       [0.2548776 , 0.90155705, 0.33829417, 0.42327077, 0.05699772,
        0.98734958, 0.14150483, 0.69118792, 0.74878936, 0.60010713,
        0.47825791, 0.21059183, 0.58842315, 0.72991839, 0.3413619 ,
        0.72166985, 0.72353001, 0.87893935, 0.90598493, 0.60021669]])

In [68]:
np.random.randint(5)

4

In [69]:
np.random.randint(2,20)

13

In [70]:
np.random.rand(2,4)

array([[0.16239248, 0.07866252, 0.05717624, 0.37032416],
       [0.85779036, 0.79736554, 0.59678804, 0.23643977]])

In [74]:
np.random.rand(2,3,4)

array([[[0.05013242, 0.87404807, 0.33680787, 0.18457158],
        [0.20772515, 0.46641569, 0.58669415, 0.37669483],
        [0.71654789, 0.58723886, 0.14668541, 0.68945868]],

       [[0.29164833, 0.70527606, 0.34920769, 0.54740353],
        [0.79461781, 0.98765311, 0.16147629, 0.4370794 ],
        [0.70860113, 0.40383823, 0.2654211 , 0.90225117]]])

In [75]:
np.random.randint(2,20)

18

In [77]:
np.random.randint(0,1)

0

In [79]:
np.random.randint(10,20,5)

array([10, 12, 10, 16, 19])

In [80]:
np.random.randint(1,6,4)

array([4, 2, 5, 4])

In [81]:
np.random.randint(3)

0

In [82]:
np.random.rand(3)

array([0.06850375, 0.54265897, 0.90456055])

In [84]:
np.random.randint(1)

0

In [85]:
np.random.randint(30,20,10)

ValueError: low >= high

In [86]:
np.random.randint(10,10,5)

ValueError: low >= high

In [87]:
np.random.randint(-30,20,10)

array([-26, -11,  -1, -23,   9,  15, -29,  -7, -18,  -9])

In [88]:
np.random.randint(20,30,10)

array([27, 24, 23, 28, 28, 26, 24, 24, 20, 20])

In [100]:
np.random.randint(5,9)

5

In [101]:
np.random.randint(10,21,3)

array([17, 17, 19])

In [102]:
np.random.randint(1,12,10)

array([11,  1, 11,  8,  1,  8,  5,  4,  8,  3])

In [103]:
np.random.randint(10,40,(10,10))

array([[16, 16, 25, 34, 10, 35, 30, 36, 23, 31],
       [23, 28, 35, 16, 26, 20, 32, 34, 19, 37],
       [25, 27, 19, 24, 33, 11, 21, 36, 33, 20],
       [39, 13, 25, 11, 19, 33, 23, 31, 20, 27],
       [32, 19, 20, 28, 16, 34, 12, 20, 29, 30],
       [21, 24, 25, 26, 20, 13, 39, 20, 18, 26],
       [31, 21, 10, 24, 14, 39, 24, 21, 29, 26],
       [37, 13, 17, 38, 20, 24, 22, 19, 22, 17],
       [20, 22, 11, 15, 19, 11, 25, 39, 10, 35],
       [10, 18, 18, 20, 33, 27, 25, 36, 26, 11]])

In [104]:
np.random.randint(10,30,(4,4))

array([[14, 11, 12, 25],
       [17, 18, 27, 28],
       [25, 25, 11, 22],
       [22, 15, 18, 28]])

In [105]:
np.random.randint(1,100,(12,12))

array([[22, 38, 81, 13, 24, 10, 83, 28, 20, 19, 15, 75],
       [34, 20, 28, 65, 69, 71, 18, 14, 20, 50, 26,  5],
       [70, 16, 71, 66, 83, 47, 96, 87, 29, 80, 17, 49],
       [16, 11, 61, 91, 48, 20, 69, 35, 58, 98,  9, 96],
       [23, 39, 29, 97, 74, 57, 74, 73, 73, 18, 77, 66],
       [26, 58, 65, 65, 70, 47, 39, 34, 51, 63,  6, 43],
       [21,  3,  6,  8, 64, 30, 86, 21, 67, 48, 17, 19],
       [ 3, 78, 45, 60, 29, 66, 88, 59, 38, 41, 45, 30],
       [67, 98, 57, 72, 35, 76, 52, 74, 42, 86, 65, 87],
       [ 8, 39, 84, 86, 93, 84, 57, 20, 12, 40, 39, 93],
       [66, 39, 90, 17, 80, 73, 63, 97, 51, 80, 76, 77],
       [19, 77, 71, 15, 48, 60, 81, 78, 83, 91,  7, 61]])

In [108]:
np.random.randint(1,4,(2,2,3))

array([[[2, 3, 3],
        [3, 1, 1]],

       [[1, 3, 1],
        [1, 3, 2]]])

In [110]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [113]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [114]:
np.arange(1,13).reshape(5,10)

ValueError: cannot reshape array of size 12 into shape (5,10)

In [116]:
b = np.random.randint(10,20,(5,4))
b

array([[13, 19, 15, 19],
       [16, 14, 16, 10],
       [14, 16, 17, 12],
       [10, 16, 19, 10],
       [11, 18, 10, 14]])

In [117]:
type(b)

numpy.ndarray

In [118]:
b[:]

array([[13, 19, 15, 19],
       [16, 14, 16, 10],
       [14, 16, 17, 12],
       [10, 16, 19, 10],
       [11, 18, 10, 14]])

In [119]:
b[1:3]

array([[16, 14, 16, 10],
       [14, 16, 17, 12]])

In [120]:
b[1:2]

array([[16, 14, 16, 10]])

In [121]:
b[1,2]

16

In [122]:
b[1,3]

10

In [123]:
b

array([[13, 19, 15, 19],
       [16, 14, 16, 10],
       [14, 16, 17, 12],
       [10, 16, 19, 10],
       [11, 18, 10, 14]])

In [124]:
b[1:-1]

array([[16, 14, 16, 10],
       [14, 16, 17, 12],
       [10, 16, 19, 10]])

In [125]:
b[2:3]

array([[14, 16, 17, 12]])

In [126]:
b[0:-2]

array([[13, 19, 15, 19],
       [16, 14, 16, 10],
       [14, 16, 17, 12]])

In [127]:
b

array([[13, 19, 15, 19],
       [16, 14, 16, 10],
       [14, 16, 17, 12],
       [10, 16, 19, 10],
       [11, 18, 10, 14]])

In [128]:
b[0,2]

15

In [129]:
b[-5:-3]

array([[13, 19, 15, 19],
       [16, 14, 16, 10]])

In [130]:
b[-5,-3]

19

In [131]:
b[-4,2]

16

In [132]:
np.random.randint(10,20,(4,4))

array([[10, 12, 11, 10],
       [18, 10, 18, 18],
       [13, 19, 15, 12],
       [10, 19, 11, 16]])

In [133]:
b

array([[13, 19, 15, 19],
       [16, 14, 16, 10],
       [14, 16, 17, 12],
       [10, 16, 19, 10],
       [11, 18, 10, 14]])

In [134]:
b[-4,-2]

16

In [135]:
b[-4:-2]

array([[16, 14, 16, 10],
       [14, 16, 17, 12]])

In [136]:
b[:]

array([[13, 19, 15, 19],
       [16, 14, 16, 10],
       [14, 16, 17, 12],
       [10, 16, 19, 10],
       [11, 18, 10, 14]])

In [137]:
b[::-1]

array([[11, 18, 10, 14],
       [10, 16, 19, 10],
       [14, 16, 17, 12],
       [16, 14, 16, 10],
       [13, 19, 15, 19]])

# Operations

In [138]:
a = np.random.randint(10,20,10)
a

array([13, 14, 19, 18, 17, 12, 12, 18, 12, 17])

In [139]:
id(a)

2344244252080

In [140]:
arr

array([0, 1, 2, 3, 4, 5])

In [142]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[34, 23, 76, 63, 27, 46, 66, 91, 33, 19],
       [ 2, 88, 79, 26, 82,  0,  4, 44,  6, 24],
       [72,  3, 24, 92, 70, 45, 68,  3, 14, 96],
       [62, 46, 57,  8,  8, 47, 50, 13, 34, 28],
       [81, 13, 55, 87, 76, 34, 52, 16,  1, 73],
       [58, 46,  0, 87, 94,  0, 40, 11, 74, 88],
       [47, 99,  4, 18, 72, 70, 88, 61, 92, 27],
       [12, 41, 15, 67, 75, 20, 20, 84, 55, 44],
       [98, 89, 52, 62, 21, 60, 33, 57,  0, 77],
       [28, 91, 69, 30, 35, 49, 12, 19, 96, 70]])

In [143]:
arr

array([0, 1, 2, 3, 4, 5])

In [144]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [145]:
arr[:4]

array([0, 1, 2, 3])

In [146]:
arr2[:]

array([[34, 23, 76, 63, 27, 46, 66, 91, 33, 19],
       [ 2, 88, 79, 26, 82,  0,  4, 44,  6, 24],
       [72,  3, 24, 92, 70, 45, 68,  3, 14, 96],
       [62, 46, 57,  8,  8, 47, 50, 13, 34, 28],
       [81, 13, 55, 87, 76, 34, 52, 16,  1, 73],
       [58, 46,  0, 87, 94,  0, 40, 11, 74, 88],
       [47, 99,  4, 18, 72, 70, 88, 61, 92, 27],
       [12, 41, 15, 67, 75, 20, 20, 84, 55, 44],
       [98, 89, 52, 62, 21, 60, 33, 57,  0, 77],
       [28, 91, 69, 30, 35, 49, 12, 19, 96, 70]])

In [147]:
arr2[0:5]

array([[34, 23, 76, 63, 27, 46, 66, 91, 33, 19],
       [ 2, 88, 79, 26, 82,  0,  4, 44,  6, 24],
       [72,  3, 24, 92, 70, 45, 68,  3, 14, 96],
       [62, 46, 57,  8,  8, 47, 50, 13, 34, 28],
       [81, 13, 55, 87, 76, 34, 52, 16,  1, 73]])

In [148]:
arr2[1,4]

82

In [149]:
arr2[-5,5]

0

In [150]:
arr2[-5,-5]

0

In [151]:
arr2[-1,-2]

96

In [152]:
arr2

array([[34, 23, 76, 63, 27, 46, 66, 91, 33, 19],
       [ 2, 88, 79, 26, 82,  0,  4, 44,  6, 24],
       [72,  3, 24, 92, 70, 45, 68,  3, 14, 96],
       [62, 46, 57,  8,  8, 47, 50, 13, 34, 28],
       [81, 13, 55, 87, 76, 34, 52, 16,  1, 73],
       [58, 46,  0, 87, 94,  0, 40, 11, 74, 88],
       [47, 99,  4, 18, 72, 70, 88, 61, 92, 27],
       [12, 41, 15, 67, 75, 20, 20, 84, 55, 44],
       [98, 89, 52, 62, 21, 60, 33, 57,  0, 77],
       [28, 91, 69, 30, 35, 49, 12, 19, 96, 70]])

In [153]:
arr2[::-1]

array([[28, 91, 69, 30, 35, 49, 12, 19, 96, 70],
       [98, 89, 52, 62, 21, 60, 33, 57,  0, 77],
       [12, 41, 15, 67, 75, 20, 20, 84, 55, 44],
       [47, 99,  4, 18, 72, 70, 88, 61, 92, 27],
       [58, 46,  0, 87, 94,  0, 40, 11, 74, 88],
       [81, 13, 55, 87, 76, 34, 52, 16,  1, 73],
       [62, 46, 57,  8,  8, 47, 50, 13, 34, 28],
       [72,  3, 24, 92, 70, 45, 68,  3, 14, 96],
       [ 2, 88, 79, 26, 82,  0,  4, 44,  6, 24],
       [34, 23, 76, 63, 27, 46, 66, 91, 33, 19]])

In [154]:
arr2[::-2]

array([[28, 91, 69, 30, 35, 49, 12, 19, 96, 70],
       [12, 41, 15, 67, 75, 20, 20, 84, 55, 44],
       [58, 46,  0, 87, 94,  0, 40, 11, 74, 88],
       [62, 46, 57,  8,  8, 47, 50, 13, 34, 28],
       [ 2, 88, 79, 26, 82,  0,  4, 44,  6, 24]])

In [155]:
arr2[::-3]

array([[28, 91, 69, 30, 35, 49, 12, 19, 96, 70],
       [47, 99,  4, 18, 72, 70, 88, 61, 92, 27],
       [62, 46, 57,  8,  8, 47, 50, 13, 34, 28],
       [34, 23, 76, 63, 27, 46, 66, 91, 33, 19]])

In [156]:
arr2[::-4]

array([[28, 91, 69, 30, 35, 49, 12, 19, 96, 70],
       [58, 46,  0, 87, 94,  0, 40, 11, 74, 88],
       [ 2, 88, 79, 26, 82,  0,  4, 44,  6, 24]])

In [157]:
arr2[::-5]

array([[28, 91, 69, 30, 35, 49, 12, 19, 96, 70],
       [81, 13, 55, 87, 76, 34, 52, 16,  1, 73]])

In [158]:
arr2[:-3]

array([[34, 23, 76, 63, 27, 46, 66, 91, 33, 19],
       [ 2, 88, 79, 26, 82,  0,  4, 44,  6, 24],
       [72,  3, 24, 92, 70, 45, 68,  3, 14, 96],
       [62, 46, 57,  8,  8, 47, 50, 13, 34, 28],
       [81, 13, 55, 87, 76, 34, 52, 16,  1, 73],
       [58, 46,  0, 87, 94,  0, 40, 11, 74, 88],
       [47, 99,  4, 18, 72, 70, 88, 61, 92, 27]])

In [159]:
arr

array([0, 1, 2, 3, 4, 5])

In [160]:
arr.max()

5

In [161]:
arr.min()

0

In [162]:
arr.mean()

2.5

In [163]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [165]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [166]:
from numpy import *
a = array([1,5,13,4,9,6])
median(a)

5.5

In [167]:
arr

array([0, 1, 2, 3, 4, 5])

In [168]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [169]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [171]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [176]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [174]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [175]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [177]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [178]:
arr


array([0, 1, 2, 3, 4, 5])

In [179]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [180]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [181]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [182]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [183]:
arr.reshape(6,2)

ValueError: cannot reshape array of size 6 into shape (6,2)

In [184]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [185]:
arr

array([0, 1, 2, 3, 4, 5])

In [186]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing

In [188]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
row = 4
col = 5

In [190]:
mat[row,col]

45

In [191]:
mat[4,5]

45

In [192]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [193]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [194]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [195]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [198]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [199]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [200]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [202]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [203]:
row

4

In [204]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [206]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [208]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [209]:
mat[1,4]

14

In [210]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [211]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [212]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [214]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [216]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [218]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [219]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [220]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [222]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [223]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [225]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

# Getting a part of matrix

In [226]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [229]:
mat[0,1]

1

In [230]:
mat[1,6]

16

In [231]:
mat[4,9]

49

In [232]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [233]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [237]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [238]:
mat[5:3]

array([], shape=(0, 10), dtype=int32)

In [239]:
mat[2:3,5:9]

array([[25, 26, 27, 28]])

In [240]:
mat[2:6,5:9]

array([[25, 26, 27, 28],
       [35, 36, 37, 38],
       [45, 46, 47, 48],
       [55, 56, 57, 58]])

# Masking or filtering

In [241]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [242]:
id(mat)

2344244721776

In [243]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [246]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [247]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [248]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [249]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [250]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [251]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [252]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [253]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [254]:
a4 = mat[mat>=50]
a4

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [256]:
a5 = mat[mat==50]
a5

array([50])

# Python program to generate OTP

In [263]:
import random

def generate_otp(length=4):
    """ Generates a numeric OTP of a specified length."""
    digits = '0123456789'
    otp = ''.join(random.choice(digits) for _ in range(length)) 
    # _ is placeholder similiar to for i in range 
    return otp

otp_length = 4
otp = generate_otp(otp_length)
print(f" Your OTP is : {otp}")

 Your OTP is : 8172


In [265]:
def wish():
    print('Good Evening')
wish()

def wish():
    print('Good Evening')
wish()

def wish():
    print('Good Evening')
wish()

Good Evening
Good Evening
Good Evening


In [266]:
def wish():
    print('Good Evening')
wish()

wish()

wish()

Good Evening
Good Evening
Good Evening


In [267]:
list1 = ['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x00000221D01D9240>


In [268]:
list1 = ['a','b','g',1,5]
print(list1.pop())

5


In [269]:
x = [1,2,3]
y= x.copy()
x.append(4)
print(x)
print(y)

[1, 2, 3, 4]
[1, 2, 3]
