# 1.Array Creation Functions

In [1]:
import numpy as np

In [3]:
# Create an array from a list

a = np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [4]:
# Create an array with evenly spaced values

b = np.arange(0,10,2)
print("Array b:",b)

Array b: [0 2 4 6 8]


In [5]:
# Create an array filled with zeros

d = np.zeros((2, 3))
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Create an array filled with ones

e = np.ones((3,2))
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# Creating a identity matrix

f = np.eye(4,dtype=int)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# 2. Array Manipulation Functions

In [10]:
# reshape an array

a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("a1:",a1)
print("Reshaped array:",reshaped)

a1: [1 2 3]
Reshaped array: [[1 2 3]]


In [12]:
# Flatten an array RAVEL FUNCTION => flattens to 1D array

f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)
print("f1:\n",f1)
print("Flattened array:",flattened)

f1:
 [[1 2]
 [3 4]]
Flattened array: [1 2 3 4]


In [13]:
# Stack array vertically VSTACK FUNCTION 

a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print('Stacked arrays:\n',stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [15]:
# Transpose an array => changing rows to columns & vice-versa

e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


# 3. Mathematical Functions

In [18]:
# Add two arrays

g = np.array([9,25,36,49])
added = np.add(g,2)
print("Added 2 to g:",added)

Added 2 to g: [11 27 38 51]


In [19]:
# Square each element

squared = np.power(g,2)
print("Squared g:",squared)

Squared g: [  81  625 1296 2401]


In [20]:
# Square root of each element

sqrt_val = np.sqrt(g)
print("Square root of g:",sqrt_val)

Square root of g: [3. 5. 6. 7.]


In [21]:
print(a1)
print(g)

[1 2 3]
[ 9 25 36 49]


In [24]:
# Dot product of two arrays

a2 = np.array([1,2,3])
dot_product = np.dot(a2,g)
print("Dot product of a2 and g:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [25]:
# Dot product of two arrays

a1 = np.array([1,2,3])
dot_product = np.dot(a,a1)
print("Dot product of a and a1:",dot_product)

Dot product of a and a1: 14


# 4.Statistical Functions

In [26]:
s =np.array([1,2,3,4,5])
mean = np.mean(s)
print("Mean of s:",mean)

Mean of s: 3.0


In [27]:
std_dev =np.std(s)
print("Standard deviation of s:",std_dev)

Standard deviation of s: 1.4142135623730951


In [28]:
min_ = np.min(s)
print("Min of s",min_)

Min of s 1


In [29]:
max_ = np.max(s)
print("Max of s",max_)

Max of s 5


# 5. Linear Algebra Functions

In [31]:
matrix = np.array([[1,3],[4,7]])
matrix

array([[1, 3],
       [4, 7]])

# 6. Random sampling Functions

In [32]:
random_vals = np.random.rand(3)
print("Random Values:",random_vals)

Random Values: [0.589708   0.13485274 0.84770267]


In [37]:
np.random.seed(0)   # set seed for reproductibility
                    # same random numbers are generated for every run

random_vals = np.random.rand(3)
print("Random Values:",random_vals)

Random Values: [0.5488135  0.71518937 0.60276338]


In [38]:
rand_ints = np.random.randint(0,10,5)
print("Random integers:",rand_ints)

Random integers: [3 7 9 3 5]


In [40]:
np.random.seed(0)     # set seed for reproductibility
                      # same random integers are generated for every run


rand_ints = np.random.randint(0,10,5)
print("Random integers:",rand_ints)

Random integers: [5 0 3 3 7]


# 7. Boolean & Logical Functions

In [46]:
# all - checks if all elements are True

logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [44]:
logical_test = np.array([False,False,False])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [47]:
any_true = np.any(logical_test)
print("Any elements true:",any_true)

Any elements true: True


# 8. Set Operations

In [48]:
# intersection of two arrays

set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
print("Intersection of sets a & b :",intersection)

Intersection of sets a & b : [3 4]


In [49]:
# union of two sets

union = np.union1d(set_a,set_b)
print("Union of sets a & b :",union)

Union of sets a & b : [1 2 3 4 5 6]


# 9. Array Attribute Functions

In [55]:
a = np.array(([1,2,3,4],[5,6,7,8]))
shape = a.shape
size = a.size
dimensions = a.ndim
dtype = a.dtype

print("Array:\n",a)
print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape of a: (2, 4)
Size of a: 8
Number of dimensions of a: 2
Data type of a: int32


# 10. Other Functions

In [57]:
copied_array = np.copy(a)
print("Copied Array:\n",copied_array)

Copied Array:
 [[1 2 3 4]
 [5 6 7 8]]


In [58]:
array_size_in_bytes = a.nbytes
print("Size of Array a in bytes:",array_size_in_bytes)

Size of Array a in bytes: 32


In [59]:
# Check if two arrays share memory

shared = np.shares_memory(a,copied_array)
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
