In [4]:
import numpy as np

In [5]:
np.zeros((3,5,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

# Rand function

In [6]:
rand(3,2)

NameError: name 'rand' is not defined

In [7]:
random.rand(2)

NameError: name 'random' is not defined

In [8]:
# np =package; random =module; rand = function
# rand() is a function that creates random samples from a uniform distribution over [0, 1)

np.random.rand(2)

array([0.24250052, 0.74697921])

In [9]:
np.random.rand(3)

array([0.86337862, 0.90706816, 0.61137275])

In [13]:
# for every run , random number changes

np.random.rand(2,3)

array([[0.78109573, 0.85286653, 0.36500269],
       [0.92730611, 0.19447457, 0.46765772]])

In [19]:
# from [0,3)

np.random.randint(3)

2

In [20]:
# 2=> inclusive ; 10=>exclusive

np.random.randint(2,10)

9

In [23]:
# for 3 random numbers

np.random.randint(2,10,3)

array([2, 2, 3])

In [24]:
# for 4 random numbers

np.random.randint(2,10,4)

array([2, 4, 2, 3])

In [ ]:
# syntax = randint(low, high=None, size=None, dtype=int)

In [27]:
np.random.randint(-30,20,10)

array([ 19,   3,   4,   8, -28,  14,  -7,   0,  -7, -16])

In [29]:
np.random.randint(10,40,(10,10))

array([[14, 35, 14, 13, 19, 32, 35, 11, 30, 30],
       [35, 33, 37, 18, 10, 22, 18, 20, 37, 29],
       [26, 29, 16, 12, 28, 13, 16, 39, 32, 25],
       [29, 32, 26, 15, 18, 31, 21, 24, 23, 20],
       [33, 12, 20, 26, 26, 31, 14, 13, 16, 36],
       [36, 15, 20, 30, 30, 38, 21, 35, 20, 21],
       [13, 27, 16, 17, 13, 12, 38, 39, 37, 37],
       [13, 39, 19, 35, 12, 28, 16, 23, 39, 36],
       [18, 28, 30, 21, 16, 32, 34, 35, 37, 36],
       [17, 30, 13, 26, 15, 37, 31, 13, 18, 23]])

In [31]:
m = np.random.randint(10,40,(10,10))
m

array([[24, 29, 10, 24, 37, 32, 36, 15, 39, 10],
       [23, 13, 21, 11, 12, 17, 13, 35, 24, 29],
       [38, 27, 13, 23, 24, 20, 18, 30, 12, 10],
       [34, 33, 35, 16, 15, 25, 10, 23, 25, 18],
       [26, 32, 14, 18, 28, 35, 23, 35, 14, 23],
       [34, 27, 34, 21, 33, 19, 32, 26, 18, 19],
       [14, 36, 22, 26, 33, 24, 34, 16, 14, 22],
       [38, 17, 35, 25, 21, 21, 16, 23, 10, 14],
       [39, 10, 17, 33, 14, 10, 18, 27, 23, 12],
       [13, 34, 15, 11, 10, 35, 27, 11, 32, 28]])

# Reshape function

In [33]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [34]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
# 3x3 not possible for size 6
# mxn matrix not possible for size l if (m*n > l)

arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [36]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [37]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

# slicing in matrix

In [42]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 11, 13, 10],
       [11, 10, 16, 13],
       [12, 18, 12, 14],
       [10, 17, 19, 13],
       [13, 11, 18, 16]])

In [43]:
b[:]

array([[12, 11, 13, 10],
       [11, 10, 16, 13],
       [12, 18, 12, 14],
       [10, 17, 19, 13],
       [13, 11, 18, 16]])

In [44]:
b[1:4]

array([[11, 10, 16, 13],
       [12, 18, 12, 14],
       [10, 17, 19, 13]])

In [46]:
b[-1:]

array([[13, 11, 18, 16]])

In [47]:
b[:-1]

array([[12, 11, 13, 10],
       [11, 10, 16, 13],
       [12, 18, 12, 14],
       [10, 17, 19, 13]])

In [49]:
b[1:3]

array([[11, 10, 16, 13],
       [12, 18, 12, 14]])

In [50]:
b

array([[12, 11, 13, 10],
       [11, 10, 16, 13],
       [12, 18, 12, 14],
       [10, 17, 19, 13],
       [13, 11, 18, 16]])

In [53]:
# calling an element => matrix[row, column]

b[1,2]

16

In [54]:
b[1,-1]

13

# NumPy operations

In [55]:
arr

array([0, 1, 2, 3, 4, 5])

In [56]:
arr.max()

5

In [57]:
arr.min()

0

In [58]:
arr.mean()

2.5

In [59]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [60]:
arr.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [61]:
from numpy import *
arr = ([0,1,2,3,4,5])
median(arr)

2.5

In [63]:
from numpy import *
arr = ([0,1,2,3,4,5])
mode(arr)

NameError: name 'mode' is not defined

In [66]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [67]:
mat[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
mat[4,5]

45

In [70]:
row = 5
column = 6

In [77]:
mat[:column]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [78]:
mat[row]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [72]:
mat[:,column]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [75]:
# to print row

mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [76]:
# to print a column

mat[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [79]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [80]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [81]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [82]:
mat[2:6,2:4]

# 2:6 = row 2to5 + 2:4 = column 2to3 ; printing a section of matrix

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [83]:
mat[1:2,2:4]

array([[12, 13]])

In [84]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

# Masking or Filter

In [85]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [86]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [88]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [89]:
mat[mat >= 50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [90]:
mat[mat == 60]

array([60])

In [92]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])