# NUMPY

In [1]:
import numpy as np

In [2]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [3]:
import numpy as np    # assigning np as alias for NumPy; for a shorter syntax

In [5]:
np.__version__

'1.26.4'

# Creating a list

In [6]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


# NumPy functions

In [12]:
np.arange()

TypeError: arange() requires stop to be specified.

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [19]:
np.arange(10,30,2,3)   # max 3 arguments - start,stop,step in arange()

TypeError: Cannot interpret '3' as a data type

In [21]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(20,8)      

# start argument(1st) should be less than stop argument(2nd) or else empty array is created
# if start is greater than stop; then step argument(3rd) should be negative for non empty array

array([], dtype=int32)

In [22]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [24]:
np.arange(20,8,-1)

# 1st arg > 2nd arg ; step arg is negative => non-empty array

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9])

In [25]:
n = np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [27]:
np.zeros(3)

# creates float zeroes array

array([0., 0., 0.])

In [28]:
np.zeros(3, dtype = int)

# creating a int type zeros array
# hyperparamter tuning: float to int datatype

array([0, 0, 0])

In [30]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((5,3))

# 2D array (rows,column)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
nd=np.zeros((5,9), dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
len(nd)

# len of array gives no of row

5

In [39]:
np.ones(3)

# creates array with 1's as its elements

array([1., 1., 1.])

In [40]:
np.ones(3, dtype = int)

array([1, 1, 1])

In [48]:
nd1 = np.ones((10,10), dtype=int)
nd1

# 10x10 matric with 1's 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [43]:
np.three(3)

# np has only zeros and ones as its functions

AttributeError: module 'numpy' has no attribute 'three'

In [44]:
arr

array([0, 1, 2, 3, 4, 5])

In [45]:
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [49]:
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])